# API-based Image Captioning Configuration

# API Captioning Settings
api_captioning:
  # API configuration
  api_endpoint: "https://generativelanguage.googleapis.com/v1beta"  # Gemini API endpoint
  api_key_env_var: "GEMINI_API_KEY"       # Environment variable for API key
  model_name: "gemini-2.5-flash"          # Gemini model for image captioning

  # Generation parameters
  max_tokens: 150                         # Maximum tokens in response
  temperature: 0.7                        # Temperature for generation (0.0-2.0)

  # Request configuration
  timeout: 30                             # Request timeout in seconds
  max_retries: 3                          # Maximum number of retries
  retry_delay: 1.0                        # Delay between retries in seconds
  batch_size: 1                           # Number of concurrent API calls

  # Rate limiting configuration (Google Gemini API Free Tier limits)
  rate_limits:
    rpm: 15                               # Requests per minute (Free tier: 15)
    tpm: 1000000                          # Tokens per minute (Free tier: 1M)
    rpd: 1500                             # Requests per day (Free tier: 1500)
    max_concurrent_requests: 5            # Maximum concurrent requests (safe limit)

  # Processing behavior
  overwrite_existing: false               # Whether to overwrite existing caption files

# Prompt Configuration
prompts:
  system_prompt: "You are an expert at describing people in images. Provide concise, accurate descriptions focusing on visible characteristics."
  user_prompt_template: "Describe this person in detail, focusing on their appearance, clothing, and any visible characteristics. Keep the description under 50 words."

# Path Configuration for API Captioning
paths:
  processed_data_dir: "./data/processed"

# Output Structure
output_structure:
  cropped_persons_dir: "cropped_persons"

# Cost tracking (optional - for usage monitoring)
cost_tracking:
  enabled: true
  token_cost_per_1k: 0.01                 # Cost per 1000 tokens (adjust based on API pricing)
  image_cost_per_request: 0.002           # Cost per image request (adjust based on API pricing)
