# Bio Data Extraction Configuration
batch_processing: false
batch_size: 10

processing_bio_types: ["my_biodata"]

file_processing:
  # Input paths for different bio data types
  my_biodata:
    input_path: "data/raw/my_biodata"
    output_path: "data/processed/my_biodata"
    images_output_path: "data/processed/my_biodata"
  ppl_biodata:
    input_path: "data/raw/ppl_biodata/rahi_matrimony"
    output_path: "data/processed/ppl_biodata/rahi_matrimony"
    images_output_path: "data/processed/ppl_biodata/rahi_matrimony"
  supported_formats: ["pdf", "jpg", "jpeg", "png", "bmp", "tiff", "gif", "docx", "doc"]

extraction:
  # Docling extraction settings
  extract_images: true
  extract_tables: true
  preserve_formatting: true
  # Image processing settings
  save_extracted_images: true
  image_formats: ["png", "jpg", "jpeg"]
  max_image_size_mb: 10

# Hugging Face models for image processing
image_processing:
  person_detection:
    model: "facebook/detr-resnet-50"
    confidence_threshold: 0.7
    device: "auto"  # auto, cpu, cuda

  image_description:
    model: "Salesforce/blip-image-captioning-large"
    max_length: 150
    device: "auto"  # auto, cpu, cuda

  # Cache settings
  cache_dir: "local/hf_cache"
  use_cache: true

bio_data_fields:
  personal_info:
    - name
    - age
    - date_of_birth
    - gender
    - location
    - nationality
    - contact_info

  education:
    - degree
    - institution
    - graduation_year
    - gpa
    - major
    - certifications

  professional:
    - current_job
    - company
    - experience_years
    - skills
    - industry
    - salary_range

  interests:
    - hobbies
    - sports
    - music
    - travel
    - books
    - movies

  lifestyle:
    - diet_preferences
    - exercise_habits
    - smoking
    - drinking
    - pets

  relationship:
    - relationship_status
    - looking_for
    - preferences
    - deal_breakers

output:
  format: "json"
  include_metadata: true
  structured_output: true
  validate_schema: true

logging:
  level: "INFO"
  file: "logs/bio_extraction.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
